name: terka
description: "Egy alkalmazás adathalászatra a MÁV szervereiről."
publish_to: 'none'
version: 26.25.2-b+262502

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  http: ^1.2.2
  xml: ^7.0.1
  url_launcher: ^6.3.1
  geolocator: ^14.0.3
  shared_preferences: ^2.3.2
  html_unescape: ^2.0.0
  package_info_plus: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: MNR2007
      fonts:
        - asset: assets/fonts/MNR2007.ttf
