name: Flutter APK Automatikus Release

# Itt adjuk meg, hogy mi váltsa ki a folyamatot
on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write 

jobs:
  build:
    name: Flutter APK Build és Feltöltés
    runs-on: ubuntu-latest 

    steps:
      # 1. Lépés: A forráskód letöltése a virtuális gépre
      - name: Forráskód letöltése
        uses: actions/checkout@v4

      # 2. Lépés: A Java környezet beállítása (ez kell az Android fordításhoz)
      - name: Java SDK beállítása
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Lépés: A Flutter környezet letöltése és beállítása
      - name: Flutter SDK beállítása
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # A stabil Flutter ágat használja

      # 4. Lépés: A projekthez szükséges csomagok letöltése
      - name: Függőségek letöltése
        run: flutter pub get

      # 5. Lépés: Az APK legyártása Release (optimalizált) módban
      - name: APK buildelése
        run: flutter build apk --release --dart-define=USE_PROXY=false

      # 6. Lépés: A legenerált APK feltöltése a GitHub Releases-be
      - name: GitHub Release létrehozása és APK csatolása
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ezt a tokent a GitHub automatikusan biztosítja a jogosultsághoz